from app.crud.app_setting import get_all_settings, get_effective_setting, get_setting, seed_defaults, set_setting
from app.crud.boilerplate import (
    create_boilerplate_pattern,
    delete_boilerplate_pattern,
    get_active_boilerplate_patterns,
    get_boilerplate_pattern,
    get_effective_boilerplate_patterns,
    list_boilerplate_patterns,
    update_boilerplate_pattern,
)
from app.crud.google_scoring_filter import (
    create_google_directory_domain,
    create_google_stopword,
    create_tfidf_stopword,
    delete_google_directory_domain,
    delete_google_stopword,
    delete_tfidf_stopword,
    get_active_google_directory_domains,
    get_active_google_stopwords,
    get_active_tfidf_stopwords,
    get_google_directory_domain,
    get_google_stopword,
    get_tfidf_stopword,
    list_google_directory_domains,
    list_google_stopwords,
    list_tfidf_stopwords,
    seed_default_directory_domains,
    seed_default_google_stopwords,
    seed_default_tfidf_stopwords,
    update_google_directory_domain,
    update_google_stopword,
    update_tfidf_stopword,
)
from app.crud.audit_log import (
    create_audit_entry,
    list_audit_for_company,
    list_recent_audit,
    record_company_changes,
)
from app.crud.collection_run import (
    complete_run,
    create_run,
    get_last_incomplete_bulk,
    list_runs,
    update_checkpoint,
)
from app.crud.company import (
    bulk_update_status,
    bulk_update_tags,
    count_companies,
    create_company,
    delete_company,
    get_category_stats,
    get_company,
    get_company_by_uid,
    get_company_stats,
    get_noga_hierarchy,
    get_taxonomy_stats,
    list_companies,
    search_clusters,
    search_keywords,
    update_company,
)
from app.crud.note import create_note, delete_note, get_note, list_notes_for_company, update_note
from app.crud.org_company_state import (
    get_or_create_org_company_state,
    get_org_company_state,
    update_org_company_state,
    update_org_google_results,
)
from app.crud.user_company_state import (
    get_or_create_user_company_state,
    get_user_company_state,
    update_personal_score_override,
    update_user_ai_results,
)
from app.crud.job_run import (
    cancel_active_csv_exports,
    create_event,
    create_job,
    delete_old_finished_jobs,
    find_active_by_dedup_key,
    get_job,
    get_latest_csv_export,
    get_next_queued_job,
    list_active_jobs,
    list_active_jobs_for_user,
    list_events,
    list_jobs,
    list_jobs_for_user,
    list_org_jobs,
    list_queued_jobs,
    has_shab_daily_run_today,
    list_waiting_llm_batches,
    mark_cancel_requested,
    mark_cancelled,
    mark_completed,
    mark_failed,
    mark_pause_requested,
    mark_paused,
    mark_running,
    mark_waiting_external,
    requeue_interrupted_jobs,
    requeue_recent_abandoned_jobs,
    resume_all_paused_jobs,
    resume_paused_job,
    update_heartbeat,
    update_progress,
)
from app.crud.cluster_registry import (
    deactivate_missing_clusters,
    get_or_create_registry_entry,
    list_active_clusters,
)
from app.crud.user import (
    authenticate,
    count_users,
    create_user,
    ensure_personal_org,
    get_or_create_oauth_user,
    get_user_by_email,
    get_user,
    hash_password,
    list_users,
    mark_email_verified,
    record_verification_sent,
    update_email,
    update_password,
    verify_password,
)

__all__ = [
    # company
    "get_company",
    "get_company_by_uid",
    "list_companies",
    "count_companies",
    "get_category_stats",
    "get_company_stats",
    "get_taxonomy_stats",
    "get_noga_hierarchy",
    "search_keywords",
    "search_clusters",
    "bulk_update_status",
    "bulk_update_tags",
    "create_company",
    "update_company",
    "delete_company",
    # note
    "get_note",
    "list_notes_for_company",
    "create_note",
    "update_note",
    "delete_note",
    # app settings
    "get_setting",
    "get_effective_setting",
    "set_setting",
    "get_all_settings",
    "seed_defaults",
    # collection run
    "create_run",
    "update_checkpoint",
    "complete_run",
    "get_last_incomplete_bulk",
    "list_runs",
    # job run
    "cancel_active_csv_exports",
    "get_latest_csv_export",
    "create_job",
    "find_active_by_dedup_key",
    "get_job",
    "get_next_queued_job",
    "list_active_jobs",
    "list_active_jobs_for_user",
    "list_jobs",
    "list_jobs_for_user",
    "list_org_jobs",
    "list_queued_jobs",
    "list_events",
    "mark_running",
    "delete_old_finished_jobs",
    "requeue_interrupted_jobs",
    "requeue_recent_abandoned_jobs",
    "resume_all_paused_jobs",
    "mark_cancel_requested",
    "mark_cancelled",
    "mark_pause_requested",
    "mark_paused",
    "resume_paused_job",
    "update_heartbeat",
    "update_progress",
    "mark_completed",
    "mark_failed",
    "create_event",
    # user
    "get_user",
    "get_user_by_email",
    "get_or_create_oauth_user",
    "list_users",
    "count_users",
    "create_user",
    "ensure_personal_org",
    "hash_password",
    "verify_password",
    "authenticate",
    "update_password",
    "update_email",
    "mark_email_verified",
    "record_verification_sent",
    # boilerplate
    "list_boilerplate_patterns",
    "get_boilerplate_pattern",
    "get_active_boilerplate_patterns",
    "get_effective_boilerplate_patterns",
    "create_boilerplate_pattern",
    "update_boilerplate_pattern",
    "delete_boilerplate_pattern",
    # google scoring filters
    "list_google_stopwords",
    "get_google_stopword",
    "get_active_google_stopwords",
    "create_google_stopword",
    "update_google_stopword",
    "delete_google_stopword",
    "list_google_directory_domains",
    "get_google_directory_domain",
    "get_active_google_directory_domains",
    "create_google_directory_domain",
    "update_google_directory_domain",
    "delete_google_directory_domain",
    "list_tfidf_stopwords",
    "get_tfidf_stopword",
    "get_active_tfidf_stopwords",
    "create_tfidf_stopword",
    "update_tfidf_stopword",
    "delete_tfidf_stopword",
    # cluster registry
    "get_or_create_registry_entry",
    "deactivate_missing_clusters",
    "list_active_clusters",
    # audit log
    "create_audit_entry",
    "record_company_changes",
    "list_audit_for_company",
    "list_recent_audit",
    # org company state overlay
    "get_org_company_state",
    "get_or_create_org_company_state",
    "update_org_company_state",
    "update_org_google_results",
    # user company state overlay
    "get_user_company_state",
    "get_or_create_user_company_state",
    "update_user_ai_results",
    "update_personal_score_override",
]
