#!/usr/bin/env bash
# join-home-node.sh — joins this machine as a k3s agent via Hetzner private networking
#
# Usage (run on the target node as root or via sudo):
#   sudo bash join-home-node.sh <CP_PRIVATE_IP> <K3S_TOKEN> <NODE_PRIVATE_IP> [NODE_NAME]
#
# Arguments:
#   CP_PRIVATE_IP      Private IP of app1 (e.g. 10.0.1.10)
#   K3S_TOKEN          K3s join token (sudo cat /var/lib/rancher/k3s/server/node-token on app1)
#   NODE_PRIVATE_IP    Private IP of this node in the same Hetzner network
#   NODE_NAME          Kubernetes node name (default: hostname -s)
#
# What this script does:
#   1. Removes any previous k3s agent installation.
#   2. Writes /etc/rancher/k3s/config.yaml for ML scheduling and private VXLAN.
#   3. Waits for control-plane API reachability on private IP.
#   4. Installs the k3s agent and joins via private network.
#
# After this script completes, run on app1:
#   kubectl get nodes -o wide
#   kubectl label node <NODE_NAME> workload=ml location=cloud --overwrite
#   kubectl taint node <NODE_NAME> workload=ml:NoSchedule --overwrite

set -euo pipefail

CP_PRIVATE_IP="${1:?Usage: $0 <CP_PRIVATE_IP> <K3S_TOKEN> <NODE_PRIVATE_IP> [NODE_NAME]}"
K3S_TOKEN="${2:?Missing K3S_TOKEN}"
NODE_PRIVATE_IP="${3:?Missing NODE_PRIVATE_IP}"
NODE_NAME="${4:-$(hostname -s)}"

if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: run as root or via sudo" >&2
  exit 1
fi

echo "=== Step 1: Remove old k3s agent (if present) ==="

if [ -f /usr/local/bin/k3s-agent-uninstall.sh ]; then
  echo "Uninstalling previous k3s agent..."
  /usr/local/bin/k3s-agent-uninstall.sh
  sleep 5
else
  echo "No previous k3s agent found."
fi

echo ""
echo "=== Step 2: Write k3s agent config ==="

mkdir -p /etc/rancher/k3s
cat > /etc/rancher/k3s/config.yaml <<EOF
# Generated by join-home-node.sh — do not edit manually
node-name: "$NODE_NAME"
node-ip: "$NODE_PRIVATE_IP"
flannel-iface: enp7s0
node-label:
  - workload=ml
  - location=cloud
node-taint:
  - workload=ml:NoSchedule
EOF
echo "Wrote /etc/rancher/k3s/config.yaml"

echo ""
echo "=== Step 3: Wait for control-plane API ==="
until nc -z "$CP_PRIVATE_IP" 6443 2>/dev/null; do
  echo "Control plane not yet reachable at ${CP_PRIVATE_IP}:6443"
  sleep 5
done

echo ""
echo "=== Step 4: Install k3s agent ==="

curl -sfL https://get.k3s.io | \
  K3S_URL="https://${CP_PRIVATE_IP}:6443" \
  K3S_TOKEN="$K3S_TOKEN" \
  sh -s - agent

echo ""
echo "=== Done ==="
echo ""
echo "The node '$NODE_NAME' should appear in 'kubectl get nodes' on app1 within ~30 s."
echo ""
echo "On app1, verify and re-apply labels/taints:"
echo "  kubectl get nodes -o wide"
echo "  kubectl label node ${NODE_NAME} workload=ml location=cloud --overwrite"
echo "  kubectl taint node ${NODE_NAME} workload=ml:NoSchedule --overwrite"
echo "  kubectl describe node ${NODE_NAME} | grep -E 'Taints|workload=|location='"
