#!/usr/bin/env bash
# join-home-node.sh — joins this machine as a k3s agent via Tailscale
#
# Usage (run on the home server as root or via sudo):
#   sudo bash join-home-node.sh <CP_TAILSCALE_IP> <K3S_TOKEN> <TAILSCALE_AUTH_KEY> [HOSTNAME]
#
# Arguments:
#   CP_TAILSCALE_IP    Tailscale IP of app1  (tailscale ip -4  on app1)
#   K3S_TOKEN          K3s join token        (sudo cat /var/lib/rancher/k3s/server/node-token  on app1)
#   TAILSCALE_AUTH_KEY Reusable Tailscale auth key from admin.tailscale.com
#   HOSTNAME           Tailscale/node hostname (default: ubuntuserverhome)
#
# What this script does:
#   1. Installs Tailscale if absent, joins with --accept-routes so the node can reach
#      the Hetzner private subnet (10.0.1.0/24) via Tailscale subnet routing.
#      Tailscale DNS is disabled to avoid conflicts with K3s CoreDNS.
#   2. Removes any previous k3s agent installation.
#   3. Writes /etc/rancher/k3s/config.yaml with the correct flannel + node-ip flags.
#   4. Installs the k3s agent (connects to CP via Tailscale IP).
#
# After this script completes, run on app1:
#   kubectl get nodes -o wide
#   kubectl label node <HOSTNAME> workload=ml location=home --overwrite
#   kubectl taint node <HOSTNAME> workload=ml:NoSchedule --overwrite
#
# Networking architecture (no Tailscale required for Hetzner-to-Hetzner traffic):
#   app1 <-> db1  : Flannel VXLAN via Hetzner private NIC (enp7s0, 10.0.1.x)
#   home <-> cloud: Flannel VXLAN via Tailscale
#     - home sends VXLAN to 10.0.1.x  → routed by Tailscale subnet route (--accept-routes)
#     - cloud sends VXLAN to home TS IP → direct Tailscale peer connection

set -euo pipefail

CP_TAILSCALE_IP="${1:?Usage: $0 <CP_TAILSCALE_IP> <K3S_TOKEN> <TAILSCALE_AUTH_KEY> [HOSTNAME]}"
K3S_TOKEN="${2:?Missing K3S_TOKEN}"
TAILSCALE_AUTH_KEY="${3:?Missing TAILSCALE_AUTH_KEY}"
NODE_HOSTNAME="${4:-ubuntuserverhome}"

if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: run as root or via sudo" >&2
  exit 1
fi

echo "=== Step 1: Tailscale ==="

if ! command -v tailscale &>/dev/null; then
  echo "Installing Tailscale..."
  curl -fsSL https://tailscale.com/install.sh | sh
fi

echo "Joining Tailscale as '${NODE_HOSTNAME}'..."
tailscale up \
  --authkey="$TAILSCALE_AUTH_KEY" \
  --hostname="$NODE_HOSTNAME" \
  --accept-routes \
  --accept-dns=false

# Wait up to 30 s for Tailscale IP
HOME_TS_IP=""
for i in $(seq 1 6); do
  HOME_TS_IP=$(tailscale ip -4 2>/dev/null || true)
  [ -n "$HOME_TS_IP" ] && break
  sleep 5
done

if [ -z "$HOME_TS_IP" ]; then
  echo "ERROR: Tailscale IP not assigned after 30 s." >&2
  echo "  Check auth key validity and admin.tailscale.com for device status." >&2
  exit 1
fi
echo "Home node Tailscale IP: $HOME_TS_IP"

echo "Verifying Tailscale connectivity to control-plane ($CP_TAILSCALE_IP)..."
if tailscale ping --c 3 "$CP_TAILSCALE_IP" &>/dev/null; then
  echo "  OK — direct Tailscale path to CP confirmed"
else
  echo "  WARNING: Tailscale ping failed. Traffic may use DERP relay." \
       "Check Hetzner firewall UDP 41641 and admin.tailscale.com."
fi

echo ""
echo "=== Step 2: Remove old k3s agent (if present) ==="

if [ -f /usr/local/bin/k3s-agent-uninstall.sh ]; then
  echo "Uninstalling previous k3s agent..."
  /usr/local/bin/k3s-agent-uninstall.sh
  sleep 5
else
  echo "No previous k3s agent found."
fi

echo ""
echo "=== Step 3: Write k3s agent config ==="

mkdir -p /etc/rancher/k3s
cat > /etc/rancher/k3s/config.yaml <<EOF
# Generated by join-home-node.sh — do not edit manually
node-ip: "$HOME_TS_IP"
node-external-ip: "$HOME_TS_IP"
flannel-iface: tailscale0
node-label:
  - workload=ml
  - location=home
node-taint:
  - workload=ml:NoSchedule
EOF
echo "Wrote /etc/rancher/k3s/config.yaml"

echo ""
echo "=== Step 4: Install k3s agent ==="

curl -sfL https://get.k3s.io | \
  K3S_URL="https://${CP_TAILSCALE_IP}:6443" \
  K3S_TOKEN="$K3S_TOKEN" \
  sh -s - agent

echo ""
echo "=== Done ==="
echo ""
echo "The node '$NODE_HOSTNAME' should appear in 'kubectl get nodes' on app1 within ~30 s."
echo ""
echo "On app1, verify and re-apply labels/taints:"
echo "  kubectl get nodes -o wide"
echo "  kubectl label node ${NODE_HOSTNAME} workload=ml location=home --overwrite"
echo "  kubectl taint node ${NODE_HOSTNAME} workload=ml:NoSchedule --overwrite"
echo "  kubectl describe node ${NODE_HOSTNAME} | grep -E 'Taints|workload=|location='"
echo ""
echo "IMPORTANT — one-time Tailscale admin step (if not already done):"
echo "  admin.tailscale.com → Machines → app1 → Edit route settings → approve 10.0.1.0/24"
echo "  admin.tailscale.com → Machines → db1  → Edit route settings → approve 10.0.1.0/24"
echo "  (These are the subnet routes that allow this home node to reach Hetzner cluster IPs)"
